# Generated by Django 3.0.4 on 2020-03-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemidi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_tp',
            name='img',
            field=models.ImageField(default='jjj', upload_to='info_tp_img'),
            preserve_default=False,
        ),
    ]
