# Generated by Django 3.0.4 on 2020-03-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemidi', '0002_info_tp_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_tp',
            name='img',
            field=models.ImageField(upload_to='info_tp_img/'),
        ),
    ]
